### ISSUE TITLE
railway-images vercel app is giving 502 error

### ISSUE THREAD

**Issue by praveeno** [railwayapp/railway-images#1]
[https://railway-images-vercel.vercel.app/](https://railway-images-vercel.vercel.app/ )
is currently throwing 502, 

> Code: NO_RESPONSE_FROM_FUNCTION

![image](https://user-images.githubusercontent.com/19618730/95656905-ef87fd00-0b2e-11eb-968b-6d5d88b506de.png)

**Comment by coffee-cup** [comment]
Fixed now (a while ago actually. I didn't see this issue, my bad) 😄
